apiVersion: v1
kind: ConfigMap
metadata:
  name: photo-configmap
data:
  NODE_ENV: "production"
  PORT: "3000"
  MONGODB_AUTH_URI: "mongodb://front-service:27017/artgallery"
  MONGODB_FEEDBACK_URI: "mongodb://front-service:27017/artgallery"
  MONGODB_URI: "mongodb://front-service:27017"