apiVersion: v1
kind: ConfigMap
metadata:
  name: photo-configmap
data:
  NODE_ENV: "production"
  PORT: "3000"
  MONGODB_URI: "mongodb://mongo-user:mongo-pass@front-service:27017/artgallery?authSource=admin"