apiVersion: v1
kind: Service
metadata:
  name: haproxy-lb
  namespace: lijaz-namespace
  annotations:
    metallb.universe.tf/address-pool: "private-vpc"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.1.169   # IP assigned to HAProxy EC2
  ports:
    - port: 80
      targetPort: 80