apiVersion: apps/v1
kind: Deployment
metadata:
  name: photo-app
  labels:
    app: photo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photo-app
  template:
    metadata:
      name: photo-app
      labels:
        app: photo-app
    spec:               # <-- this was missing
      containers:
        - name: photo-container
          image: lijazs/photo-app:v1.0.0
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: photo-secret
                  key: MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: photo-secret
                  key: MONGO_PASSWORD
            - name: MONGO_HOST
              value: front-service
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DB
              value: artgallery